# Generated by Django 4.2.4 on 2024-02-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="content",
            field=models.CharField(max_length=5000),
        ),
    ]
