# Generated by Django 4.2.4 on 2024-02-03 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
